import ChequeControl from '@/components/ChequeControl'
import Header from '@/components/Header'
import Head from 'next/head'
import React from 'react'

export default function Dashboard() {
    return (
        <>
            <Head>
                <title>LISKO TECH - Cheques</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <ChequeControl
                headerLine="Estornados"
                display="none"
                endPoint="cheques/linha"
                submitOnMount="true"
            />

            <ChequeControl
                headerLine="Sem Destino"
                display="none"
                endPoint="cheques/sem-destino"
                submitOnMount="true"
            />

            <ChequeControl
                headerLine="Próximos Vencimentos"
                display="none"
                endPoint="cheques/a-vencer"
                submitOnMount="true"
            />
        </>
    )
}
