
import Button from '@/components/Button';
import Input from '@/components/Input';
import User from '@/api/UserService';
import React, { useEffect, useState } from 'react'
import { toast } from 'react-toastify';
import styles from '../../styles/perfil.module.css'
import Head from 'next/head';
import Header from '@/components/Header';
import decode from 'jwt-decode';

const Perfil = () => {

    const notifySuccess = () => toast.success("Cadastrado com sucesso!");
    const notifyFailure = () => toast.error("Erro ao cadastrar usuário!");

    const [nome, setNome] = useState('');
    const [senha, setSenha] = useState('');
    const [contraSenha, setContraSenha] = useState('');
    const [id, setId] = useState(null);

    const handleNome = (e) => {
        setNome(e.target.value);
    }

    const handleSenha = (e) => {
        setSenha(e.target.value);
    }

    const handleContraSenha = (e) => {
        setContraSenha(e.target.value);
    }

    const handleSubmit = async (e) => {
        e.preventDefault();
        let checkCadastro = false;

        if (senha !== contraSenha) {
            alert('Senhas devem ser iguais!');
            return;
        }

        const user = {
            id: id,
            nome: nome,
            senha: senha
        };

        try {
            let data = await User.editUser(user);

            if (data) {
                checkCadastro = true;
            }
        } catch (error) {
            console.error('Erro ao cadastrar usuário:', error);
        }

        if (checkCadastro) {
            notifySuccess();
            
            setNome('');
            setSenha('');
            setContraSenha('');
        } else {
            notifyFailure();
        }
    };

    useEffect(() => {
        const token = document.cookie
            .split('; ')
            .find((row) => row.startsWith('token='))
            ?.split('=')[1];

        const { id } = decode(token);
        console.log(id);
        setId(id);
    }, []);

    return (
        <>
            <Head>
                <title>LISKO TECH - Cheques</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Header />
            <div className={styles.editWrapper}>
                <h1 className={styles.editTitle}>MENU USUÁRIO</h1>
                <form className={styles.editForm} onSubmit={handleSubmit}>
                    <div className={styles.editFormField}>
                        <label htmlFor="nome">Nome</label>
                        <Input type="text" name="nome" id="nome" value={nome} onChange={handleNome} placeholder="Nome" />
                    </div>
                    <div className={styles.editFormField}>
                        <label htmlFor="senha">Senha</label>
                        <Input type="password" name="senha" id="senha" value={senha} onChange={handleSenha} placeholder="********" required />
                    </div>
                    <div className={styles.editFormField}>
                        <label htmlFor="contrasenha">Repita sua senha</label>
                        <Input type="password" name="contrasenha" id="contrasenha" value={contraSenha} onChange={handleContraSenha} placeholder="********" required />
                    </div >
                    <Button type="submit">Editar</Button>
                </form>
            </div>
        </>
    )
}

export default Perfil