import Head from 'next/head'
import Header from '@/components/Header';
import ChequeControl from '@/components/ChequeControl';
import ChequeControlEstornados from '@/components/ChequeControlEstornados';


export default function Home() {
  
  
  
  return (
    <>
      <Head>
        <title>LISKO TECH - Cheques</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <ChequeControl 
        headerLine="Sem Destino"
        display="none"
        endPoint="cheques/sem-destino"
        submitOnMount="true"
        type="destino"
      />

      {/* <ChequeControl 
        headerLine="Estornados"
        display="none"
        endPoint="cheques/linha"
        submitOnMount="true"
        type="estorno"
      /> */}

    <ChequeControlEstornados 
    headerLine="Estornados"
    display="none"
    endPoint="cheques/linha"
    submitOnMount="true"
    type="estorno"
    />
    
      <ChequeControl 
        headerLine="Próximos Vencimentos"
        display="none"
        endPoint="cheques/a-vencer"
        submitOnMount="true"
        type="next"
      />
    </>
  )
}