<<<<<<< HEAD
import Head from 'next/head'
import Header from '@/components/Header';
import ChequeControl from '@/components/ChequeControl';

=======
import Button from '@/components/Button';
import HeaderLogin from '@/components/HeaderLogin';
import Link from 'next/link';
import styles from '../styles/IndexLayout.module.css';
>>>>>>> 34ef091f73f675edfe04bdf32de5ff7d7c83260e

export default function Home() {
  return (
    <>
<<<<<<< HEAD
      <Head>
        <title>LISKO TECH - Cheques</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <ChequeControl 
        headerLine="Sem Destino"
        display="none"
        endPoint="cheques/sem-destino"
        submitOnMount="true"
      />

      <ChequeControl 
        headerLine="Estornados"
        display="none"
        endPoint="cheques/linha"
        submitOnMount="true"
      />
      
      <ChequeControl 
        headerLine="Próximos Vencimentos"
        display="none"
        endPoint="cheques/a-vencer"
        submitOnMount="true"
      />
=======
      <HeaderLogin />
      <div className={styles.mainWrapper}>
        <h1 className={styles.mainTitle}>Seja bem-vindo!</h1>
        <h2 className={styles.mainSubTitle}>Caso já possua cadastro, clique no botão de Login.</h2>
        <div className={styles.btns}>
        <Link href="/home/login"><Button>Login</Button></Link>
        <Link href="/home/cadastro"><Button>Cadastre-se</Button></Link>
        </div>
      </div>
>>>>>>> 34ef091f73f675edfe04bdf32de5ff7d7c83260e
    </>
  )
}